version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    environment:
      - ./api-gateway/.env
    networks:
      - microservices-net

  orchestrator:
    build: ./orchestrator
    ports:
      - "3004:3004"
    environment:
      - ./orchestrator/.env
    networks:
      - microservices-net
      
  notification-service:
    build: ./notification-service
    ports:
      - "3005:3005"
    environment:
      - ./notification-service/.env
    networks:
      - microservices-net
    volumes:
      - notification-logs:/usr/src/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  
  activity-service :
    build:
      context: ./activity-service
    ports:
      - "3002:3002"
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb+srv://prashath:17112001@cluster0.xfs2y.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
    networks:
      - microservices-net
    restart: always 

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - DATABASE_URL=postgresql://Davdiii:Azerty123@user-db:5432/userServiceDB?serverVersion=17&charset=utf8
    depends_on:
      user-db:
        condition: service_healthy
    networks:
      - microservices-net

  user-db:
    image: postgres:17
    environment:
      POSTGRES_DB: userServiceDB
      POSTGRES_USER: Davdiii
      POSTGRES_PASSWORD: Azerty123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Davdiii -d userServiceDB"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  notification-logs:
  user_db_data:
  postgres_data:

networks:
  microservices-net:
    driver: bridge